[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
log.workspace = true
env_logger.workspace = true
toml.workspace = true
clap.workspace = true
thiserror.workspace = true
crossbeam-channel.workspace = true

[features]
default = ["module_file_in", "module_file_out"]
module_file_out = []
module_file_in = []
